"""Initial migration.

Revision ID: 4d0748aca998
Revises: 868fbfc16732
Create Date: 2024-04-02 23:01:39.846096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0748aca998'
down_revision = '868fbfc16732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
