"""Initial migration.

Revision ID: 868fbfc16732
Revises: cb7edfb9cc46
Create Date: 2024-04-02 21:51:18.280464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868fbfc16732'
down_revision = 'cb7edfb9cc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('dataset_used_for_learning')
        batch_op.drop_column('type')
        batch_op.drop_column('task')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('dataset_used_for_learning', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
